#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | bash:help)
    help_content_func () {
      declare desc="return help_content string"
      cat<<help_content
    bash, Spawn bash shell
help_content
    }

    help_content_func
    ;;

  bash)
    /usr/bin/env bash "${@:2}"
    ;;

  scp | rsync)
    eval $@
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
